### ISSUE TITLE
貌似没能正常工作，侧边栏无变化

### ISSUE THREAD

**Issue by WsinGithub** [sethyuan/logseq-plugin-tabbed-sidebar#1]
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/55137994/3fad5b76-5650-401b-90b7-ed268cf2ea0f)
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/55137994/941080ca-a9d0-4c06-b7ac-29b2d617540d)

win10 0.9.8

**Comment by sethyuan** [comment]
console里有报了什么错吗？感觉像是插件的安装问题。要先开开发者模式，用插件里的“手动载入插件”加载插件文件夹。

**Comment by WsinGithub** [comment]
有报错：
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/55137994/16dfa5b9-8ed7-438f-aed9-6e0f72cd0f9a)

其他操作和设置大概率没问题：
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/55137994/b1fa8d5e-3f53-4651-b0a1-171d8a5236b9)

**Comment by sethyuan** [comment]
你这里的日志看不出啥来。很奇怪，我这边都是正常的，启动也没啥特殊的。你是不是下载错包了？应该用releases下的包哦。

https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/releases

**Comment by WsinGithub** [comment]
> 你这里的日志看不出啥来。很奇怪，我这边都是正常的，启动也没啥特殊的。你是不是下载错包了？应该用releases下的包哦。
> 
> https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/releases

还真是...直接下的 master🤒

现在正常了！
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/55137994/57973f42-5f02-4632-adfb-58421fdc9027)
