### ISSUE TITLE
tab index issue with shift click  

### ISSUE THREAD

**Issue by leeyaunlong** [sethyuan/logseq-plugin-tabbed-sidebar#2]
If I have 3 tabs (named  t1, t2, t3) , and active tab is t3. And Main page is M1.
When I shift click t1 , Main page has no any changes.
When I shift click t2, the main page will jump to t1.
click t3 will jump to t2.

Please fix it.

**Comment by sethyuan** [comment]
What version do you have? I'm unable to reproduce it following your steps. Can you make a short recording of your case?
