### ISSUE TITLE
和Tabs插件有冲突

### ISSUE THREAD

**Issue by artemith** [sethyuan/logseq-plugin-tabbed-sidebar#3]
打开tabbed sidebar插件后，tabs插件就无法使用，tabs点击无反应
![Snipaste_2023-06-30_09-03-58](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/14881525/8f45eece-7171-4174-9633-bdc53e8b17e2)

**Comment by sethyuan** [comment]
有空我安装个试试看。

**Comment by artemith** [comment]
感谢seth大佬

**Comment by sethyuan** [comment]
我测试下来没有问题呀，用的默认的设置，主题是Woz。

**Comment by artemith** [comment]
我刚才试了下，也没有问题，可能是早上那会儿电脑的问题
