### ISSUE TITLE
New tab overlays existing tab

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tabbed-sidebar#5]
If I have 1 tab open, e.g. Contents, and then want to open a 2<sup>nd</sup> tab, it sits on top of the 1<sup>st</sup> one.
Edit: it only happens to the Contents tab that gets overridden/overlayd. If I open more pages in the sidepane the tabs open next to each other.

Is there a way to pin those sidepane tabs?

**Comment by sethyuan** [comment]
>  it only happens to the Contents tab that gets overridden/overlayd.
It follows the original sidebar's behavior, this can't be changed.

> Is there a way to pin those sidepane tabs?
Nope, but you can just leave them opened.

**Comment by DutchPete** [comment]
Sorry for my late reply, I did not receive a notification of yours.

If I want to have the Contents tab open + 1 page, how do I do that since opening the page in the sidebar overlays the Contents tab?

**Comment by sethyuan** [comment]
@DutchPete ,

Check this video:

https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/3410293/befc18ed-d111-4074-9f2c-a7f60ba0ce0b

**Comment by DutchPete** [comment]
OK, got it.
That vid also implicitly explains why I should not hide the top row that is above the tabbed row (#4).
Many thanks for your patience 😀
