### ISSUE TITLE
無法與Nord Theme佈景相容

### ISSUE THREAD

**Issue by nate-chen-ty** [sethyuan/logseq-plugin-tabbed-sidebar#6]
有Tabbed Sidebar這個plugin真的很好用
但是它似乎與Nord Theme這個佈景不相容
切換到Nord Theme佈景以後，Tab就不見了
很可惜沒辦法同時擁有這兩個好用的工具

**Comment by sethyuan** [comment]
有些themes改动较大，不太好处理。我有空先看一下具体情况再说吧。

**Comment by sethyuan** [comment]
我看了下，是因为themes把`.sidebar-item-list`改成position absolute导致的，这样会把tab bar给遮住。我感觉这个兼容改动可能在theme项目里做会比较好，插件去覆盖theme的样式不太合适，这样其它的themes想要调插件的样式就困难了。

**Comment by nate-chen-ty** [comment]
感謝您的快速回覆，我是logseq的新手，您的好多插件我都有安裝，都非常實用，謝謝

Seth Yuan ***@***.***>於 2023年8月3日 週四，上午9:16寫道：

**Comment by sethyuan** [comment]
那这个ticket我先关了。
