### ISSUE TITLE
适配0.9.14

### ISSUE THREAD

**Issue by saccohuo** [sethyuan/logseq-plugin-tabbed-sidebar#7]
tab显示错位，目录下面显示的是另一个tab的内容
![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/13887263/70c365ef-fc00-4dbd-be3e-6373ef85acc1)

**Comment by sethyuan** [comment]
已适配，稍微测试了一下，应该没有问题了。BTW，后面还会增强 Tabbed Sidebar 的使用体验。
